### ISSUE TITLE
Getting task report from file undefined

### ISSUE THREAD

**Issue by sand314** [simondel/sonar-buildbreaker-vsts#12]
I am getting this error after the update yesterday

**Comment by sand314** [comment]
This seems to be the result of this tool looking into the temp folder

**Comment by simondel** [comment]
Could you give me some more info on your sonarqube version, the task version and the version of your sonarqube tasks?

**Comment by simondel** [comment]
I have updated the extension. Could you see if that helps you?

For SonarQube the new version is 8.* (https://github.com/simondel/sonar-buildbreaker-vsts/releases/tag/SonarQube-build-breaker-8.0.0)
For SonarCloud the new version is 2.* (https://github.com/simondel/sonar-buildbreaker-vsts/releases/tag/SonarCloud-build-breaker-2.0.2)

**Comment by sand314** [comment]
*Sonarqube version 7.5.0.20543
My tasks...
- script: npm run sonar
    displayName: 'Run SonarQube'
  
  - task: sonar-buildbreaker@8
    displayName: 'Checking SonarQube Results'
    inputs:
        SonarQube: 'Front-Ends'

*I'm currently building angular project through my pipeline. 

*This is what i am getting back...*

[section]Starting: Checking SonarQube Results
Number of analyses in this build: 0
Summary of statusses: 
##[section]Finishing: Checking SonarQube Results

**Comment by simondel** [comment]
Thanks for the info! Could you take a look at #11? There may be an issue with your general SonarQube setup.

**Comment by sand314** [comment]
Hello thanks for the quick response.

There isn't any issue with running sonar scanner for these projects, one of the first tasks I run is 
- script: npm install -g sonarqube-scanner
    displayName: 'Install SonarQube

The command to run sonarqube uses sonar-project.properties This is how sonar-scanner pushes the report up to sonarqube which is working. I believe the sonar build breaker tool is unable to find the report-task.txt located in *\_work\1\s\ .scannerwork 

Best
sand314

**Comment by simondel** [comment]
If you run the build with debug enabled, what does the logging from the 'publish quality gate' task say? How many analyses can it find?

**Comment by sand314** [comment]
Since I am using sonar scanner to run the analysis there doesn't need to be the publish quality gate. Sonar scanner will publish my analysis during run. There is install sonar scanner step then a run sonar step for angular/typescript analysis. My other pipelines are .net core. The sonar steps are prepare, run analysis, and publish. These pipelines work as intended.  

This is the result from running sonar scanner.
INFO: Analysis report generated in 924ms, dir size=1 MB
INFO: Analysis reports compressed in 549ms, zip size=342 KB
INFO: Analysis report uploaded in 47ms
INFO: ANALYSIS SUCCESSFUL

**Comment by simondel** [comment]
I understand that the tasks are able to upload the result to the SonarQube server. I however doubt that they'll be able to report the result to the build summary. 

As displayed here: https://github.com/simondel/sonar-buildbreaker-vsts/issues/11#issuecomment-522433164

The _Publish Quality Gate_ task is responsible for adding the result to the build summary and I don't think that's happening in your .net core builds (if you also have the issues with my extension in that build).

Could you add the Publish Quality Gate task to your Angular build to see what happens?

**Comment by sand314** [comment]
Nice! We got it working. Thanks! I omitted the install and run for sonarqube and replaced those two steps with these tasks -
- task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Front-Ends'
      scannerMode: 'CLI'
      configMode: 'file'
         
  - task: SonarQubeAnalyze@4
  
  - task: SonarQubePublish@4
    inputs:
        pollingTimeoutSec: '300'

Thanks again!

**Comment by simondel** [comment]
Glad to hear that you were able to resolve the issue :)
