### ISSUE TITLE
Azure Devops Server 2019

### ISSUE THREAD

**Issue by DeadlyDragon** [simondel/sonar-buildbreaker-vsts#14]
Version of Build Breaker: 8.0.0
Version of SonarQube: 4.7.2

Tasks always succeeding but getting the following:

Getting task report from file undefined
(node:7688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: path must be a string or Buffer

or

Number of analyses in this build: 0
Summary of statusses: 
##[section]Finishing: Break build on quality gate failure

**Comment by simondel** [comment]
Hi, this is a duplicate. See #13
