### ISSUE TITLE
Build breaker cannot find reports

### ISSUE THREAD

**Issue by msweaver** [simondel/sonar-buildbreaker-vsts#15]
Hi Simon. 

I'm using sonar 6.7 and build breaker 8 and I'm getting the following output from build breaker:
```
##[section]Starting: Break build on quality gate failure
==============================================================================
Task         : SonarQube build breaker
Description  : Break the build when the quality gate fails.
Version      : 8.0.0
Author       : Simon de Lang
Help         : 
==============================================================================
Number of analyses in this build: 0
Summary of statusses: 
##[section]Finishing: Break build on quality gate failure
```

I can see from a previous step that the report-tasks.txt is being written to the following path:
13:40:25.010 DEBUG: Report metadata written to `D:\VSTS\Agents\A\_work\179\.sonarqube\out\.sonar\report-task.txt`

Any ideas? Cheers!

**Comment by simondel** [comment]
Hey! If you use the _Publish Quality Gate_ task, please check if the reports end up in your summary. I think they don't.

There's a bug with SonarSource right now that is placing the report in the wrong folder for some versions of SonarQube. More info can be found here: https://community.sonarsource.com/t/sonarqubebuildsummary-md-file-empty-with-the-publish-quality-gate-result-step-in-azure-devops/13305/2

**Comment by gt97** [comment]
Hi Simon,

 SonarQUbe just released 4.8.0 version for Sinar Publish. I tried it and now the issue is solved.
 I still face "Number of analyses in this build: 0"

I have a pipeline in dev.azure.com and Sonar installed locally. The agent is local and has access from the build machine. The analisys is done by sonar, but build breaker says 0 analyses in this build.

My steps are:
- task: SonarQubePrepare@4
- task: Maven@3 (with sonarQubeRunAnalysis: true)
- task: SonarQubePublish@4
- task: sonar-buildbreaker@8

Kindly
Gianluca

**Comment by simondel** [comment]
From their changelog:
> Added fallback search for report-task.txt in previous location for SQ instances < 7.2.0

I'll copy their changes later today/tomorrow. Thanks for the heads-up!

**Comment by gt97** [comment]
Hi Simon,

 Yes, I can confirm my Sonar version is 7.0

Kindly
Gianluca

**Comment by simondel** [comment]
I've just published v8.1.0 of the extension. @gt97 and @msweaver does that solve your issues?

**Comment by gt97** [comment]
I can confirm the extension works correctly. I made the test below (to test if it works even with multiple projects in the analysis)

It works perfectly.
Test one project:
1. test: maven - sonar analysis fails 
   expected result: sonarbreaker -> KO
	result: Test OK
2. test: maven  - sonar analysis passes
   expected result: sonarbreaker -> OK
    result: Test OK
3. test: esql - sonar analysis fails
   expected result: sonarbreaker -> KO
	result: Test OK
4. test: esql - sonar analysis passes
   expected result: sonarbreaker -> OK
	result: Test OK

Test two projects in the same build:
5. test: maven - sonar analysis fails and esql - sonar analysis fails
   expected result: sonarbreaker -> KO
	result: Test OK
6. test: maven - sonar analysis passes and esql - sonar analysis fails
   expected result: sonarbreaker -> KO
	result: Test OK
7. test: maven - sonar analysis fails and esql - sonar analysis passes
   expected result: sonarbreaker -> KO
	result: Test OK
8. test: maven - sonar analysis passes and esql - sonar analysis passes
   expected result: sonarbreaker -> OK
	result: Test OK

Thank you
Kindly
Gianluca

**Comment by modmoto** [comment]
Hi @simondel 
We have the same issue, too. 

We have Sonar 8.0, the plugins are on 4.6.3 and we have the 8.1 build breaker version. The gate is also published in the build but we also get the error, that the build breaker does not find the reports like gt97 mentioned.

Is there anything we are missing?

p.s. can not upload screenshots right now, I will try again at home.

**Comment by modmoto** [comment]
Hi,

updating to the 4.8 version of the sonar tasks fixed the issue for us. Just in case anyone stumbles on this one ;)

Greetings
Simon
