### ISSUE TITLE
SonarCloud build breaker is failling due to SQL mapping error

### ISSUE THREAD

**Issue by leonidasnascimento** [simondel/sonar-buildbreaker-vsts#19]
Hi all,

I'm trying to run a pipeline on Azure DevOps & found a new error on SonarCloud Build Breaker: it's failling appearently due to a SQL error. The log is attached.
[SonarCloud Build Breaker Error Log.txt](https://github.com/simondel/sonar-buildbreaker-vsts/files/5027459/SonarCloud.Build.Breaker.Error.Log.txt)

**Comment by simondel** [comment]
Hi @leonidasnascimento  this seems to be an issue in SonarCloud. Is it still present?
