### ISSUE TITLE
SonarQube analysis failing

### ISSUE THREAD

**Issue by simondel** [simondel/sonar-buildbreaker-vsts#2]
@remkoseelig mentioned in #1 that the has the following issue:
> Using VSTS and SonarQube 6.7.1 I the build/plugin fails with: "Cannot read property 'task' of undefined".

@nboeckmann has this same issue but with TFS:
> Hey,
>
>I'm having the same issue as @remkoseelig and I'm using the 7.x version. I'm still getting the same error message as he does: "Cannot read property 'task' of undefined".
>
>I'm using SQ Server 6.7.1 and I can see in the access.log that the queries are made OK and that content is returned. I've also validated the output of the queries and they seem to be ok considering what you have written earlier in this post.
>
>Do you have any idea what can be the reason for it?

**Comment by simondel** [comment]
I have improved the logging. Could you try it out and let me know what the logging says? The task version (seen in the TFS/VSTS build logs) should be at least 7.0.3.

**Comment by nboeckmann** [comment]
Hey,

I'm getting the following now:

`2018-07-11T06:18:27.8639311Z Getting task report from file C:\Build\vsts-agent\_work\64\.sonarqube\out\.sonar\report-task.txt
2018-07-11T06:18:27.8795597Z Retrieving analysisId from https://build05.omada.dk/api/ce/task?id=AWSH_Y8wmgROYPRroi7m
2018-07-11T06:18:27.9264304Z ##[error]Unhandled: Cannot read property 'statusCode' of undefined`

The API call returns the following:
`{"task":{"id":"AWSH_Y8wmgROYPRroi7m","type":"REPORT","componentId":"AWJR4HgmLP8d4uocX1dc","componentKey":"SaaS","componentName":"SaaS","componentQualifier":"TRK","analysisId":"AWSH_Zd9yan4xzvBNbqL","status":"SUCCESS","submittedAt":"2018-07-11T08:18:18+0200","submitterLogin":"TFSSERVICE","startedAt":"2018-07-11T08:18:20+0200","executedAt":"2018-07-11T08:18:26+0200","executionTimeMs":5782,"logs":false,"hasScannerContext":true,"organization":"default-organization"}}`

Thank you for your Help.

**Comment by simondel** [comment]
@nboeckmann thanks! That error occurs because the server did not give any response at all it seems. I have added a check to see if we even get a response from the server if the callback gets hit. Could you try it again? (New version is 7.0.4.)

**Comment by nboeckmann** [comment]
@simondel It was a certificate issue!! I'm using an SSL certificate for my SonarQube instance which is issued by an AD CA which was apparently not trusted by the nodejs request module.

The error message I got was `2018-07-12T19:47:48.6974768Z ##[error]Unable to get a result! It has value undefined and a possible error is Error: unable to get local issuer certificate
2018-07-12T19:47:48.6974768Z ##[error]Unhandled: Cannot read property 'statusCode' of undefined`

I'm now accepting the root and intermediate certificate of the CA which have issued the SSL certificate and it works!

Thank you so much for your help!

**Comment by simondel** [comment]
Awesome! Glad to hear that the logging finally worked! I'll close this issue for now.
