### ISSUE TITLE
letsencrypt cert issues

### ISSUE THREAD

**Issue by ccicrlucas** [simondel/sonar-buildbreaker-vsts#24]
![image](https://user-images.githubusercontent.com/67339044/135640175-54ab0ee3-0f58-4b67-8406-71abc50411fb.png)
Getting a vague issue, but we're using the newest release that supposedly fixes these... is there some cache that needs cleared on the build agents or is this still actively being worked out?

**Comment by ccicrlucas** [comment]
If there's any more info I could provide to help out please let me know. And thanks for the extension 👍

**Comment by simondel** [comment]
Not quite sure! Could you rerun the pipeline using verbose logging? Perhaps that will give you some more info

**Comment by ccicrlucas** [comment]
![image](https://user-images.githubusercontent.com/67339044/135641414-d26e7e93-bc65-40b6-83ba-757e77f6cc59.png)
was just thinking of looking at the verbose output... here we go.

**Comment by stwe11** [comment]
Hi all,
set your pipeline task to 2.1.0 version
- task: sonarcloud-buildbreaker@2.1.0

**Comment by ckranthi950** [comment]
I am also getting same error in my Azure CI pipeline.

Starting: Break build on quality gate failure
==============================================================================
Task         : SonarQube build breaker
Description  : Break the build when the quality gate fails.
Version      : 8.1.1
Author       : Simon de Lang
Help         : 
==============================================================================
##[debug]Using node path: /opt/Azure-BuildAgent/externals/node/bin/node
##[debug]agent.TempDirectory=/opt/Azure-BuildAgent/_work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_SONARQUBE
##[debug]loading ENDPOINT_AUTH_c2056c3c-68dd-4298-9c16-1eb568e42d14
##[debug]loading ENDPOINT_AUTH_SCHEME_c2056c3c-68dd-4298-9c16-1eb568e42d14
##[debug]loading ENDPOINT_AUTH_PARAMETER_c2056c3c-68dd-4298-9c16-1eb568e42d14_USERNAME
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SONARQUBE_ENDPOINT
##[debug]loaded 8
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]task result: Failed
##[error]Unhandled: Unexpected token ...
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected token ...
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected token ...
Finishing: Break build on quality gate failure

**Comment by ccicrlucas** [comment]
> Hi all, set your pipeline task to 2.1.0 version
> 
> * task: sonarcloud-buildbreaker@2.1.0

We're using on prem sonarqube, not cloud. using 8.* and it's picking up the new 8.1.1 release

**Comment by ckranthi950** [comment]
when we switch task version from 8 to 7 it's working..

**Comment by simondel** [comment]
It almost seems as if it's using an old version of NodeJS and the `...` spread operator is not known.

If either of you have access to the file system of the build agent, could you try placing console.log statements in the code to figure out where it's crashing?

**Comment by ckranthi950** [comment]
Which NodeJS version we need use on build agent.

Thanks,
***@***.***

Kranthi Cherukuri | ALM Systems Engineer
Plot No. 137, Sector-44, Gurgaon 122002, India
CELL: +91- 9502221990
***@***.***

**Comment by jclements2** [comment]
We use this task in all of our pipelines (thousands) and they are all failing as well. Changing the task version to 7.* is working for us in the interim.

**Comment by simondel** [comment]
NodeJS 8.3 should be high enough.

**Comment by ccicrlucas** [comment]
We're using node v12.13.0 on the build agent, and in the pipeline itself, actually using node tool installer version 14 for one, and 12 for another, and ... was introduced in node 8 I was reading.

**Comment by ckranthi950** [comment]
I am using NodeJS v10.14.1 and npm version v6.4.1, still build are failing with build breaker task version 8

**Comment by SanthoshYalamuri** [comment]
The same issue occurs for SonarCloud build break task.

**Comment by ccicrlucas** [comment]
So, not super familiar with the spread operator, and also not sure where to stick the console log statements... when scanning the files, I see the ... in 2 files - Metrics.ts inner function and Request.ts get function... but that's in the .ts file. The files for the task in the dist folder are regular javascript, and don't show the spread operator in these locations.

![image](https://user-images.githubusercontent.com/67339044/135649185-e10a489c-5b1c-414f-b242-cd5fd455bc69.png)

![image](https://user-images.githubusercontent.com/67339044/135649223-4ce0fca9-f921-442b-9c8e-4b6162c5681e.png)

![image](https://user-images.githubusercontent.com/67339044/135649342-29a5de31-7ab1-4ec3-96b6-9eeb089cc3ef.png)

Any recommendation on where to add console.log statements?

**Comment by yfrindel** [comment]
same problem since today 
![image](https://user-images.githubusercontent.com/22955005/135651276-c46f3345-b312-425a-9395-e3f0d5f19fec.png)

**Comment by simondel** [comment]
It might be code in a dependency that was updated. I noticed that the fix the SonarQube team implemented also updated some more config for the extension.

**I have released a new version of the extension for SonarQube and SonarCloud** which includes this change (v8.1.2 and v2.1.2). Please let me know if this resolves the issue!

**Comment by ckranthi950** [comment]
Hi Simondel,

Thanks for quick fix, now issue has been resolved.

***@***.***

Thanks,
***@***.***

Kranthi Cherukuri | ALM Systems Engineer
Plot No. 137, Sector-44, Gurgaon 122002, India
CELL: +91- 9502221990
***@***.***

**Comment by ccicrlucas** [comment]
Tested the new release and works like a charm - many thanks!

**Comment by klazarus-cci** [comment]
Likewise, thanks for the quick fix and responsiveness

**Comment by SanthoshYalamuri** [comment]
Works perfectly after the upgrade. Thanks.

**Comment by yfrindel** [comment]
Many thanks for this quick update simondel, it works perfectly. Brilliant
