### ISSUE TITLE
Sonar Cloud build breaking after 2.1.1 upgrade

### ISSUE THREAD

**Issue by andreracz** [simondel/sonar-buildbreaker-vsts#26]
After the recent 2.1.1 upgrade, all our pipelines started breaking, with the error:

Starting: Break build on quality gate failure
==============================================================================
Task         : SonarCloud build breaker
Description  : Break the build when the quality gate fails.
Version      : 2.1.1
Author       : Simon de Lang
Help         : 
==============================================================================
##[error]Unhandled: Unexpected token ...
Finishing: Break build on quality gate failure

---
Is there a work around?

**Comment by stwe11** [comment]
@andreracz use version 2.1.0 on your task
check this thread 
https://github.com/simondel/sonar-buildbreaker-vsts/issues/24

**Comment by andreracz** [comment]
Thanks, that solved it as a temporary fix. Keeping this open for the definitive version.

**Comment by glauberl-ciandt** [comment]
Noticed the same issue as well.

**Comment by simondel** [comment]
Hi! This has been fixed with V2.1.2
