### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ghost** [simondel/sonar-buildbreaker-vsts#3]
I got a question, I have extension “Break build on quality gate failure” version 6.2.3, and it seems that it required has "Publish Quality Gate Result", if i disable that task i get the following error:

![image](https://user-images.githubusercontent.com/16038189/43532427-ac5ce7b8-9577-11e8-844b-ee875a7920cf.png)

But i got a problem with task Publish Quality Gate result, it taking so long to finish, despite that the task "Run Code Analysis" is finished. Why this happen? it is necessary to have the task "Publish Quality Gate Result" configured in my pipeline before “Break build on quality gate failure” task?

I have SonarQube 4.3.0.

Thanks for your help.

**Comment by simondel** [comment]
Thanks for opening this issue! The publish quality gate task is not required. It is recommended as my task may cause your build to fail if you break the quality gate. Having a link to the SonarQube analysis if that happens is useful.

Does the 'Publish Quality Gate' task work for your build? This extension officially does not support SonarQube below version 6, so I cannot guarantee that the API calls that I do will work.

I would recommend trying out version 7.x of my extension as that one works better.

**Comment by ghost** [comment]
Sorry, my mistake, my sonar version es 6.7... When i run my pipeline with the following conf, its work ok!:

![image](https://user-images.githubusercontent.com/16038189/43544502-b80ea74c-9598-11e8-96ee-a8e9374ac3bb.png)

![image](https://user-images.githubusercontent.com/16038189/43544922-0cf082c0-959a-11e8-9bc9-8cc7261bee7c.png)

When i disabled the task "Publish Quality Gate Result" i get the following error:

![image](https://user-images.githubusercontent.com/16038189/43544544-e0b95f5c-9598-11e8-9616-e22c2d16204a.png)

I upgraded the version of task "Break " to 7... And the message error changed but still its not working.

**Comment by simondel** [comment]
I believe the SonarQube tasks actually use a polling mechanism to check if the analysis is available yet. My implementation is quite lazy so it doesn't do that.

The message "The analysis did not pass the quality gate" means thaty plugin did its job. It got the data from SonarQube, but that data indicates that the build should fail because your code did not pass the quality gate.

If you have tips on how the message could be improved to make it more clear, please let me know!

**Comment by simondel** [comment]
I have updated the extension to include more information about the usage: https://marketplace.visualstudio.com/items?itemName=SimondeLang.sonar-buildbreaker

I'll close this issue for now. If you have any feedback on how the message _"The analysis did not pass the quality gate"_ could be improved, please let me know!

**Comment by tlbonds2** [comment]
Sounds good.  Thanks a lot for the support!  Much appreciated.
