### ISSUE TITLE
Execution failure with socket hang up error

### ISSUE THREAD

**Issue by guileinsighter** [simondel/sonar-buildbreaker-vsts#4]
Hi,

Our execution is suddenly failing with socket hang up error (after a few hours running) as per screen shot below as if it couldn't access/authenticate Sonarqube, though previous task (Publish Quality Gate Result) does using very same Sonarqube  endpoint.

![image](https://user-images.githubusercontent.com/17008932/54217334-32549f80-44ca-11e9-9b83-ee023a76f649.png)

Any hints?
Thanks.

**Comment by simondel** [comment]
Thanks for letting me know! I've seen a lot of strange SonarQube issues, but not this one.

How often does this happen? My code should make the same API calls as the Publish Quality Gate Result task.

Also, what version + edition are you running?

**Comment by simondel** [comment]
Since I didn't hear anything back. I'm closing this issue for now. If you still have issues using the latest version, please let me know.
