### ISSUE TITLE
Report task file not found

### ISSUE THREAD

**Issue by O-heu** [simondel/sonar-buildbreaker-vsts#8]
Since the update of the sonar plugin to version 4.7.0 we get the following error:

(node:4115) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: path must be a string or Buffer
Getting task report from file undefined

We checked the changes of the sonar plugin and recognised that the result will now placed in the tmp directory rather than the build folder.

see:
common/ts/sonarqube/TaskReport.ts 

in the following commit:
https://github.com/SonarSource/sonar-scanner-vsts/commit/956ba211b6c7ecf40e50361fc941090707cb8847#diff-3a4ea7e6eb2e6b2767e851d8f1b58b72

**Comment by simondel** [comment]
Thanks for letting me know! This issue has just been resolved: https://github.com/simondel/sonar-buildbreaker-vsts/issues/10#issuecomment-521525664
